default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: josephjung
  password:
  database: msk_lol

test:
  <<: *default
  database: msk_lol_test

production:
  <<: *default
  database: msk_lol_production
  username: msk_lol
  password: <%= ENV['MSK_LOL_DATABASE_PASSWORD'] %>
